import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local"
import "./globals.css";


export const metadata: Metadata = {
  title: "AFRIXA",
  description: "Generated by create next app",
};

const clashDisplay = localFont({
  src: './fonts/ClashDisplay-Variable.woff2', // adjust path as needed
  display: 'swap',
  variable: '--font-clash-display',
})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clashDisplay.variable}
      >
        {children}
      </body>
    </html>
  );
}
